config/routes.rb
Rails.application.routes.draw do

  root to: 'user/posts#index'


  scope module: :user do
    get "/about" => "homes#about"
    get "users/mypage" => "users#show"
    get "users/mypage/edit" => "users#edit"
    patch "users/mypage" => "users#update"
    get "users/check" => "users#check"
    patch "users/withdraw" => "users#withdraw"
    get 'search' => 'posts#search'



    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      member do
        put 'toggle_published', to: 'posts#toggle_published'
        get 'likes', to: 'likes#index'
      end

      resource :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end

  # 顧客用
    # URL /customers/sign_in ...
    devise_for :users, skip: [:passwords], controllers: {
      registrations: "user/registrations",
      sessions: 'user/sessions'
    }


  # # Set the root to your desired path after sign in
  #   devise_scope :user do
  #     authenticated :user do
  #       root 'user/homes#top', as: :authenticated_root
  #     end

  #     unauthenticated do
  #       root 'user/homes#top', as: :unauthenticated_root
  #     end


    # end






  namespace :admin do
    get '/' => 'homes#top'
    resources :comments, only: [:index, :destroy]
    resources :users, only: [:index,:new,:create,:show,:edit,:update]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :content, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def index
    @comments = Comment.all
    @users = User.all
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:content)
  end


end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'コメントが投稿されました。'
    else
      redirect_to @post, alert: 'コメントの投稿に失敗しました。'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @comment.post, notice: 'コメントが削除されました。'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end


end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <%= render "admin/side_bar" %>
    </div>
    <div class="col-8">
      <h3>コメント一覧</h3>
      <table class="table">
        <thead>
          <th>ユーザー名</th>
          <th>コメント</th>
          <th></th>
        </thead>

        <tbody>
          <% @comments.each do |comment| %>
          <tr>
            <td>
              <%= @users.find(comment.user_id).name %>
            </td>
            <td>
              <%= comment.content %>
            </td>
            <td>
              <%= button_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: '本当に削除しますか？' } %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>